# Generated by Django 5.0 on 2024-01-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_options_alter_story_username'),
        ('users', '0006_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='stories.story'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
