# Generated by Django 5.0 on 2024-01-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_rename_username_story_user'),
        ('users', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='stories.story'),
        ),
    ]
