# Generated by Django 5.0 on 2023-12-15 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stories_old', to=settings.AUTH_USER_MODEL, verbose_name='User who posted'),
        ),
    ]
