# Generated by Django 5.0 on 2024-01-02 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='User who posted'),
        ),
    ]
