# Generated by Django 5.0 on 2024-01-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_options_alter_story_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='username',
            new_name='user',
        ),
    ]
