# Generated by Django 5.0 on 2024-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_rename_username_story_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x101d39800>', primary_key=True, serialize=False),
        ),
    ]
