# Generated by Django 5.0 on 2024-01-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_alter_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.CharField(default='34067ec4-a7bb-48c8-8b11-ab5615b46272', primary_key=True, serialize=False),
        ),
    ]
