# Generated by Django 5.0 on 2024-01-24 23:11

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.CharField(default=stories.models.generate_uuid, primary_key=True, serialize=False),
        ),
    ]
